# Auto-generated by step7/pipeline.py
import os
import slicer
import vtk

CT_VOLUME_PATH = r"/Users/penelopel/Desktop/881_project/outputs/step6_case/ct_volume.nii.gz"
SEGMENTATION_PATH = r"/Users/penelopel/Desktop/881_project/outputs/step6_case/segmentation_volume.nii.gz"
SLICE_INDEX = None
CENTER_IJK = None


def _load(path, loader, label):
    if not os.path.exists(path):
        raise FileNotFoundError(f"{label} not found: {path}")
    node = loader(path)
    if node is None:
        raise RuntimeError(f"Failed to load {label} from {path}")
    return node


def _compute_slice_offset(volume_node, slice_index):
    if slice_index is None:
        return None
    matrix = vtk.vtkMatrix4x4()
    volume_node.GetIJKToRASMatrix(matrix)
    ijk = [0.0, 0.0, float(slice_index), 1.0]
    ras = matrix.MultiplyPoint(ijk)
    return ras[2]


def _add_fiducial_at_ijk(volume_node, ijk, name="Nodule_Center"):
    # Create a Markups fiducial at the given IJK coordinate (if provided).
    if ijk is None:
        return None
    if not isinstance(ijk, (list, tuple)) or len(ijk) != 3:
        return None

    matrix = vtk.vtkMatrix4x4()
    volume_node.GetIJKToRASMatrix(matrix)
    ijk_h = [float(ijk[0]), float(ijk[1]), float(ijk[2]), 1.0]
    ras = matrix.MultiplyPoint(ijk_h)

    fiducial_node = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode", name)
    fiducial_node.AddFiducialFromArray(ras)
    return fiducial_node


def main():
    print("=" * 60)
    print("Step7 · 3D Slicer automation")
    print("=" * 60)

    slicer.mrmlScene.Clear()
    layout_manager = slicer.app.layoutManager()
    layout_manager.setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)

    ct_node = _load(CT_VOLUME_PATH, slicer.util.loadVolume, "CT volume")
    ct_node.SetName("CT_Volume")
    label_node = _load(SEGMENTATION_PATH, slicer.util.loadLabelVolume, "Segmentation mask")
    label_node.SetName("Tumor_Segmentation")

    ct_display = ct_node.GetDisplayNode()
    if ct_display:
        # Lung window (roughly WW 1500, WL -500)
        ct_display.SetWindow(1500)
        ct_display.SetLevel(-500)

    label_display = label_node.GetDisplayNode()
    if label_display:
        label_display.SetAndObserveColorNodeID("vtkMRMLColorTableNodeGrey")
        label_display.SetOpacity(0.85)
        label_display.SetVisibility(True)

    slicer.util.setSliceViewerLayers(background=ct_node, label=label_node, labelOpacity=0.85)

    offset = _compute_slice_offset(ct_node, SLICE_INDEX)
    if offset is not None:
        for view_name in ("Red", "Yellow", "Green"):
            widget = layout_manager.sliceWidget(view_name)
            if widget:
                widget.sliceLogic().SetSliceOffset(offset)
        slicer.util.resetSliceViews()
        print(f"Jumped to slice index {SLICE_INDEX} (offset {offset:.2f} mm)")
    else:
        print("No slice index provided; showing first slice.")

    fiducial_node = _add_fiducial_at_ijk(ct_node, CENTER_IJK)
    if fiducial_node is not None:
        print(f"Fiducial created at CENTER_IJK: {CENTER_IJK}")

    print(f"CT volume loaded: {ct_node.GetName()}")
    print(f"Segmentation loaded: {label_node.GetName()}")
    print("=" * 60)


if __name__ == "__main__":
    main()
